version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn fastapi_app:app --host 0.0.0.0 --port 8000 --reload
    
  # 将来的にデータベース等を追加する場合
  # postgres:
  #   image: postgres:14
  #   environment:
  #     POSTGRES_DB: fastapi_db
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
