"""Fix database models

Revision ID: 07a81ab3def4
Revises: 4500627e8ce8
Create Date: 2025-07-17 07:42:22.976624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07a81ab3def4'
down_revision: Union[str, Sequence[str], None] = '4500627e8ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='課題名'),
    sa.Column('description', sa.Text(), nullable=True, comment='説明'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='プロジェクトID'),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False, comment='難易度'),
    sa.Column('max_score', sa.Integer(), nullable=True, comment='最大スコア'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='有効フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.create_table('blob_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='操作タイプ'),
    sa.Column('container_name', sa.String(length=100), nullable=False, comment='コンテナ名'),
    sa.Column('blob_name', sa.String(length=500), nullable=False, comment='Blob名'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='ファイルサイズ'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='コンテンツタイプ'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ステータス'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='ユーザーID'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='エラーメッセージ'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='操作時間'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blob_logs_id'), 'blob_logs', ['id'], unique=False)
    op.drop_index(op.f('ix_assigns_id'), table_name='assigns')
    op.drop_table('assigns')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigns',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=False, comment='ユーザー名'),
    sa.Column('assin_execution', mysql.INTEGER(), autoincrement=False, nullable=True, comment='実行'),
    sa.Column('assin_maintenance', mysql.INTEGER(), autoincrement=False, nullable=True, comment='保守'),
    sa.Column('assin_prospect', mysql.INTEGER(), autoincrement=False, nullable=True, comment='見込み'),
    sa.Column('assin_common_cost', mysql.INTEGER(), autoincrement=False, nullable=True, comment='共通(原価)'),
    sa.Column('assin_most_com_ps', mysql.INTEGER(), autoincrement=False, nullable=True, comment='大共通PS'),
    sa.Column('assin_sales_mane', mysql.INTEGER(), autoincrement=False, nullable=True, comment='営支(販管)'),
    sa.Column('assin_investigation', mysql.INTEGER(), autoincrement=False, nullable=True, comment='調検'),
    sa.Column('assin_project_code', mysql.INTEGER(), autoincrement=False, nullable=False, comment='プロジェクトコード'),
    sa.Column('assin_directly', mysql.INTEGER(), autoincrement=False, nullable=True, comment='直接'),
    sa.Column('assin_common', mysql.INTEGER(), autoincrement=False, nullable=True, comment='共通'),
    sa.Column('assin_sales_sup', mysql.INTEGER(), autoincrement=False, nullable=True, comment='営支'),
    sa.Column('month_data', mysql.JSON(), nullable=True, comment='月ごとの合計データ'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_assigns_id'), 'assigns', ['id'], unique=False)
    op.drop_index(op.f('ix_blob_logs_id'), table_name='blob_logs')
    op.drop_table('blob_logs')
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
