"""Update AssignData fields to DECIMAL type

Revision ID: 2af443aa5eb0
Revises: fb0f68c0e346
Create Date: 2025-07-18 02:54:57.737541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2af443aa5eb0'
down_revision: Union[str, Sequence[str], None] = 'fb0f68c0e346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assign_data', 'assin_execution',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='実行アサイン',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_maintenance',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='保守アサイン',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_prospect',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='見込みアサイン',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_common_cost',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='共通費アサイン',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_most_com_ps',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='最も共通PS',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_sales_mane',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='営業管理',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_investigation',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='調査',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_directly',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='直接',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_common',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='共通',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_sales_sup',
               existing_type=mysql.INTEGER(),
               type_=sa.DECIMAL(precision=10, scale=2),
               existing_comment='営業支援',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assign_data', 'assin_sales_sup',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='営業支援',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_common',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='共通',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_directly',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='直接',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_investigation',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='調査',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_sales_mane',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='営業管理',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_most_com_ps',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='最も共通PS',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_common_cost',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='共通費アサイン',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_prospect',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='見込みアサイン',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_maintenance',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='保守アサイン',
               existing_nullable=True)
    op.alter_column('assign_data', 'assin_execution',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=mysql.INTEGER(),
               existing_comment='実行アサイン',
               existing_nullable=True)
    # ### end Alembic commands ###
