"""Add assign_data table

Revision ID: 6bb3b09b77d3
Revises: d53e0ae05cf5
Create Date: 2025-07-17 07:36:28.187957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6bb3b09b77d3'
down_revision: Union[str, Sequence[str], None] = 'd53e0ae05cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False, comment='ユーザー名'),
    sa.Column('assin_execution', sa.Integer(), nullable=True, comment='実行'),
    sa.Column('assin_maintenance', sa.Integer(), nullable=True, comment='保守'),
    sa.Column('assin_prospect', sa.Integer(), nullable=True, comment='見込み'),
    sa.Column('assin_common_cost', sa.Integer(), nullable=True, comment='共通(原価)'),
    sa.Column('assin_most_com_ps', sa.Integer(), nullable=True, comment='大共通PS'),
    sa.Column('assin_sales_mane', sa.Integer(), nullable=True, comment='営支(販管)'),
    sa.Column('assin_investigation', sa.Integer(), nullable=True, comment='調検'),
    sa.Column('assin_project_code', sa.Integer(), nullable=False, comment='プロジェクトコード'),
    sa.Column('assin_directly', sa.Integer(), nullable=True, comment='直接'),
    sa.Column('assin_common', sa.Integer(), nullable=True, comment='共通'),
    sa.Column('assin_sales_sup', sa.Integer(), nullable=True, comment='営支'),
    sa.Column('month_data', sa.JSON(), nullable=True, comment='月ごとの合計データ'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assigns_id'), 'assigns', ['id'], unique=False)
    op.drop_index(op.f('ix_assignments_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_blob_logs_id'), table_name='blob_logs')
    op.drop_table('blob_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blob_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operation_type', mysql.VARCHAR(length=50), nullable=False, comment='操作タイプ'),
    sa.Column('container_name', mysql.VARCHAR(length=100), nullable=False, comment='コンテナ名'),
    sa.Column('blob_name', mysql.VARCHAR(length=500), nullable=False, comment='Blob名'),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=True, comment='ファイルサイズ'),
    sa.Column('content_type', mysql.VARCHAR(length=100), nullable=True, comment='コンテンツタイプ'),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False, comment='ステータス'),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='ユーザーID'),
    sa.Column('error_message', mysql.TEXT(), nullable=True, comment='エラーメッセージ'),
    sa.Column('operation_time', mysql.DATETIME(), nullable=True, comment='操作時間'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('blob_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_blob_logs_id'), 'blob_logs', ['id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False, comment='課題名'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='説明'),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='プロジェクトID'),
    sa.Column('difficulty_level', mysql.VARCHAR(length=20), nullable=False, comment='難易度'),
    sa.Column('max_score', mysql.INTEGER(), autoincrement=False, nullable=True, comment='最大スコア'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='有効フラグ'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新日時'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('assignments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_assignments_id'), 'assignments', ['id'], unique=False)
    op.drop_index(op.f('ix_assigns_id'), table_name='assigns')
    op.drop_table('assigns')
    # ### end Alembic commands ###
