"""create initial tables

Revision ID: c84698d55337
Revises: 
Create Date: 2025-07-17 04:40:25.421411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84698d55337'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_code', sa.String(length=255), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('user_team', sa.String(length=255), nullable=True),
        sa.Column('user_type', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('project_br_num', sa.String(length=255), nullable=True),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('project_contract_form', sa.String(length=255), nullable=True),
        sa.Column('project_sched_self', sa.String(length=255), nullable=True),
        sa.Column('project_sched_to', sa.String(length=255), nullable=True),
        sa.Column('project_type_name', sa.String(length=255), nullable=True),
        sa.Column('project_classification', sa.String(length=255), nullable=True),
        sa.Column('project_budget_no', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assigns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_name', sa.String(length=255), nullable=True),
        sa.Column('assin_execution', sa.Float(), nullable=True),
        sa.Column('assin_maintenance', sa.Float(), nullable=True),
        sa.Column('assin_prospect', sa.Float(), nullable=True),
        sa.Column('assin_common_cost', sa.Float(), nullable=True),
        sa.Column('assin_most_com_ps', sa.Float(), nullable=True),
        sa.Column('assin_sales_mane', sa.Float(), nullable=True),
        sa.Column('assin_investigation', sa.Float(), nullable=True),
        sa.Column('assin_project_code', sa.Integer(), nullable=True),
        sa.Column('assin_directly', sa.Float(), nullable=True),
        sa.Column('assin_common', sa.Float(), nullable=True),
        sa.Column('assin_sales_sup', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histograms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('histogram_ac_code', sa.String(length=255), nullable=True),
        sa.Column('histogram_ac_name', sa.String(length=255), nullable=True),
        sa.Column('histogram_pj_br_num', sa.String(length=255), nullable=True),
        sa.Column('histogram_pj_name', sa.String(length=255), nullable=True),
        sa.Column('histogram_pj_contract_form', sa.String(length=255), nullable=True),
        sa.Column('histogram_costs_unit', sa.Integer(), nullable=True),
        sa.Column('histogram_year', sa.Integer(), nullable=True),
        sa.Column('histogram_01month', sa.Float(), nullable=True),
        sa.Column('histogram_02month', sa.Float(), nullable=True),
        sa.Column('histogram_03month', sa.Float(), nullable=True),
        sa.Column('histogram_04month', sa.Float(), nullable=True),
        sa.Column('histogram_05month', sa.Float(), nullable=True),
        sa.Column('histogram_06month', sa.Float(), nullable=True),
        sa.Column('histogram_07month', sa.Float(), nullable=True),
        sa.Column('histogram_08month', sa.Float(), nullable=True),
        sa.Column('histogram_09month', sa.Float(), nullable=True),
        sa.Column('histogram_10month', sa.Float(), nullable=True),
        sa.Column('histogram_11month', sa.Float(), nullable=True),
        sa.Column('histogram_12month', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('notice_time', sa.String(length=255), nullable=True),
        sa.Column('user_name', sa.String(length=255), nullable=True),
        sa.Column('notice_text', sa.String(length=255), nullable=True),
        sa.Column('project_name', sa.String(length=255), nullable=True),
        sa.Column('notice_type', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notices')
    op.drop_table('histograms')
    op.drop_table('assigns')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
