"""Add CSV upload tables (histogram_data, project_data, user_data)

Revision ID: fb0f68c0e346
Revises: 07a81ab3def4
Create Date: 2025-07-18 02:51:34.702357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0f68c0e346'
down_revision: Union[str, Sequence[str], None] = '07a81ab3def4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histogram_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('histogram_ac_code', sa.String(length=30), nullable=False, comment='ACコード'),
    sa.Column('histogram_ac_name', sa.String(length=100), nullable=False, comment='AC名称'),
    sa.Column('histogram_pj_br_num', sa.String(length=30), nullable=False, comment='PJ枝番'),
    sa.Column('histogram_pj_name', sa.String(length=100), nullable=False, comment='PJ名称'),
    sa.Column('histogram_pj_contract_form', sa.String(length=30), nullable=False, comment='PJ契約形態'),
    sa.Column('histogram_costs_unit', sa.Integer(), nullable=False, comment='工数単位'),
    sa.Column('histogram_year', sa.Integer(), nullable=False, comment='年'),
    sa.Column('histogram_1month', sa.String(length=10), nullable=True, comment='1月'),
    sa.Column('histogram_2month', sa.String(length=10), nullable=True, comment='2月'),
    sa.Column('histogram_3month', sa.String(length=10), nullable=True, comment='3月'),
    sa.Column('histogram_4month', sa.String(length=10), nullable=True, comment='4月'),
    sa.Column('histogram_5month', sa.String(length=10), nullable=True, comment='5月'),
    sa.Column('histogram_6month', sa.String(length=10), nullable=True, comment='6月'),
    sa.Column('histogram_7month', sa.String(length=10), nullable=True, comment='7月'),
    sa.Column('histogram_8month', sa.String(length=10), nullable=True, comment='8月'),
    sa.Column('histogram_9month', sa.String(length=10), nullable=True, comment='9月'),
    sa.Column('histogram_10month', sa.String(length=10), nullable=True, comment='10月'),
    sa.Column('histogram_11month', sa.String(length=10), nullable=True, comment='11月'),
    sa.Column('histogram_12month', sa.String(length=10), nullable=True, comment='12月'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_histogram_data_id'), 'histogram_data', ['id'], unique=False)
    op.create_table('project_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_br_num', sa.String(length=30), nullable=False, comment='PJコード枝番'),
    sa.Column('project_name', sa.String(length=100), nullable=False, comment='PJ名称'),
    sa.Column('project_contract_form', sa.String(length=30), nullable=False, comment='PJ契約形態'),
    sa.Column('project_sched_self', sa.String(length=20), nullable=False, comment='予定期間(自)'),
    sa.Column('project_sched_to', sa.String(length=20), nullable=False, comment='予定期間(至)'),
    sa.Column('project_type_name', sa.String(length=30), nullable=False, comment='PJタイプ名称'),
    sa.Column('project_classification', sa.String(length=30), nullable=False, comment='PJ分類'),
    sa.Column('project_budget_no', sa.String(length=30), nullable=False, comment='実行予算見積番号'),
    sa.Column('project_valid_from', sa.String(length=20), nullable=True, comment='追加日'),
    sa.Column('project_valid_to', sa.String(length=20), nullable=True, comment='有効期限'),
    sa.Column('project_is_current', sa.Boolean(), nullable=True, comment='現行PJフラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_br_num')
    )
    op.create_index(op.f('ix_project_data_id'), 'project_data', ['id'], unique=False)
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_code', sa.String(length=30), nullable=False, comment='ユーザーコード'),
    sa.Column('user_name', sa.String(length=30), nullable=False, comment='ユーザー名'),
    sa.Column('user_team', sa.String(length=30), nullable=False, comment='所属チーム'),
    sa.Column('user_type', sa.String(length=20), nullable=True, comment='ユーザータイプ'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_code')
    )
    op.create_index(op.f('ix_user_data_id'), 'user_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_data_id'), table_name='user_data')
    op.drop_table('user_data')
    op.drop_index(op.f('ix_project_data_id'), table_name='project_data')
    op.drop_table('project_data')
    op.drop_index(op.f('ix_histogram_data_id'), table_name='histogram_data')
    op.drop_table('histogram_data')
    # ### end Alembic commands ###
